<?php
/**
 * Fontis Australia Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fontis
 * @package    Fontis_Australia
 * @author     Thai Phan
 * @copyright  Copyright (c) 2014 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<ul class="address-validator-message">
    <li class="incorrect-address-title">Address_Type address: postcode, state or suburb could not be validated:</li>
    <li class="incorrect-address">Incorrect Address</li>
</ul>
<ul class="address-validator-potentials">
    <li class="validated-address">Please select the correct address:</li>
    <li class="incorrect-address">Potential Address</li>
</ul>
<div class="address-validator-buttons">
    <button type="button" id="submit-user-x-address" value="use_selected" class="submit-button button"><span><span>Continue with selected address</span></span></button>
    <button type="button" id="submit-valid-x-address" value="use_entered" class="submit-button button"><span><span>Use entered address</span></span></button>
    <button type="button" id="cancel-invalid-x-address" value="edit_address" class="submit-button button"><span><span>Edit address</span></span></button>
</div>
<br style="clear: both">
